### ISSUE TITLE
Its not working for me on 1.6

### ISSUE THREAD

**Issue by t0chas** [linuxgurugamer/PWBFuelBalancerRestored#1]
I put the part but nothing happens
I press m or d and nothing
no extra toolbar buttons nothing

here is the log 
[KSP.log](https://github.com/linuxgurugamer/PWBFuelBalancerRestored/files/2742614/KSP.log)

i think the culprit is this
`[ERR 06:05:51.729] [ModuleManager] Post run call threw an exception in loading PWBFuelBalancerRestored, Version=0.1.5.5, Culture=neutral, PublicKeyToken=null

[EXC 06:05:51.731] ReflectionTypeLoadException: The classes in the module cannot be loaded.
	System.Reflection.Assembly.GetTypes ()
	ModuleManager.MMPatchLoader+<ProcessPatch>d__31.MoveNext ()
	UnityEngine.Logger:LogException(Exception)
	ModuleManager.Logging.UnityLogger:Exception(String, Exception)
	ModuleManager.Logging.ModLogger:Exception(String, Exception)
	ModuleManager.<ProcessPatch>d__31:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)`

this is the build id
 [config]
build id = 02395
2018.12.20 at 06:04:51 PST
Branch: master
language = en-us

Version 1.6.0

**Comment by linuxgurugamer** [comment]
Did you install the dependencies?
Full instructions are in the OP:  https://forum.kerbalspaceprogram.com/index.php?/topic/180409-15-16-pwb-fuel-balancer-restored-resource-jettisoning/

but to summarize:

Mod Dependencies: 

Click Through Blocker
ToolbarController

**Comment by t0chas** [comment]
I see, yes that did the trick.
Initially I installed with CKan and there it does not have the dependencies set.

**Comment by linuxgurugamer** [comment]
Oh, I'll have to fix that.
