### ISSUE TITLE
Numerical display and control of saved CoM

### ISSUE THREAD

**Issue by damerell** [linuxgurugamer/PWBFuelBalancerRestored#4]
I will be delighted if you close this with "this exists already, do it like this, you idiot".

I would find it useful to be able to display and edit the set CoM numerically, especially in the VAB/SPH.

I'm designing a Project Orion spaceplane, and for easy operation in space it's vital the vertical CoM stay directly level with the engines. I can use Precise Editor to display the vessel's CoM and the position of the engines, but all I can do then (AFAICT) is to stick a procedural weight on directly under the CoM and adjust it until the CoM is directly ahead of the engines, then save that CoM in PWB and remove the weight. (Of course, it can't actually _get_ the CoM there until some pulse units are used up - but for atmospheric takeoff it's OK if thrust makes it pitch up a bit).

**Comment by linuxgurugamer** [comment]
Being worked on

**Comment by damerell** [comment]
Thanks. (In practice I think will render my desire to disable an axis moot, especially if exposed to kOS, because I can just put the desired CoM in about the right place - so two thanks for the development effort of one, and sorry to open a second issue without realising the first issue would largely do what I wanted.)

**Comment by linuxgurugamer** [comment]
Fixed in 0.2.1 release
