### ISSUE TITLE
Ignore one axis

### ISSUE THREAD

**Issue by damerell** [linuxgurugamer/PWBFuelBalancerRestored#5]
Another thing I would find useful is the ability to tell the fuel balancer to simply ignore one axis altogether, or to prioritise balancing a particular axis rather than optimising for overall CoM error. Once in space, I don't care nearly as much about the fore-aft position of the CoM as I do that it stays in front of the centre of thrust, and trying to preserve a fore-aft CoM might actually compromise balancing on the up-down axis.

(Indeed, if I want to do asymmetrical aeroplane designs - which I don't, but there does seem to be a considerable interest in recreating real planes in FAR - I will be far more vexed by left-right error than either fore-aft or up-down.)

**Comment by linuxgurugamer** [comment]
Not going to happen, sorry.  I am working on an update in which you can enter absolute values, and sliders to make it easier to adjust.  But what you are asking for is currently easily done, because I would have to rewrite the entire balance section
